version: '2.0' # docker-compose version

services:

  db:
    image: postgres:9.6.6
    restart: always
    environment:
      POSTGRES_USER: marine
      POSTGRES_PASSWORD: marine
      POSTGRES_DB: marine
    ports:
      - 54321:5432

  db-init:
    build: .
    links:
      - 'db:db'

  adminer:
    image: adminer
    restart: always
    links:
      - "db:database" # postgres is reachable for adminer from web at the hostnames db and database
    ports:
      - 8081:8080