version: '2.0' # docker-compose version

services:

  db:
    image: postgres:9.6.12-alpine
    restart: always
    environment:
      POSTGRES_USER: marine
      POSTGRES_PASSWORD: marine
      POSTGRES_DB: marine
    ports:
      - 54321:5432
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c track_activity_query_size=2048 -c pg_stat_statements.track=all

  db-init:
    build: .
    volumes:
      - "./sql:/sql"
      - "~/.m2:/root/.m2"
    links:
      - "db:db"
    command: ["./wait-for-postgres.sh", "db", "marine", "marine", "marine", "./init-db.sh"]

  pghero:
    image: ankane/pghero
    restart: always
    environment:
        DATABASE_URL: postgres://marine:marine@db:5432/marine
    links:
    - "db:database" # postgres is reachable for pghero from web at the hostnames db and database
    ports:
    - 8082:8080
