version: 2.1

networks:
  db_network:
    external:
      name: network

services:
  db:
    image: postgres:9.6.6
    restart: always
    environment:
      POSTGRES_USER: marine
      POSTGRES_PASSWORD: marine
      POSTGRES_DB: marine
    networks:
      - db_network
